### PR TITLE
Add flag to disable openssh warning

### PR DESCRIPTION
**Pull request by vivianho**
I understand that there are some issues with OpenSSH 7.8 but this is not related to the blessclient itself, but rather the servers that are being presented the certificate for authentication (to my understanding). As a result, I'd like the option to disable this warning because this issue does not affect the systems we use.

@edulop91

### CODE REVIEW

**Comment by edulop91** [comment]
@vivianho what do you think about completely getting rid of this warning?

**Comment by vivianho** [comment]
I didn't implement this, so I assume the warning was added for a good reason by folks on your side. I'd be happy to get rid of the warning entirely but if it's required for your folks to ssh into your servers, leaving it there with a flag to disable is my approach.

**Comment by edulop91** [comment]
Good to remove the warning on our end too. I think reducing the complexity here by removing that warning altogether is probably better long-term.

**Comment by vivianho** [comment]
I made this PR: https://github.com/chanzuckerberg/blessclient/pull/102

You can close this PR and merge the other.

**Comment by edulop91** [comment]
Thank you!

**Pull request closed without merging**
